name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Prebuild Expo (Generate Android Folder)
        run: npx expo prebuild --platform android --clean

      - name: Patch Legacy JCenter
        run: find node_modules -name "build.gradle" -type f -exec sed -i 's/jcenter()/mavenCentral()/g' {} +

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m" -x lintVitalAnalyzeRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: advanced-expense-tracker-apk
          path: android/app/build/outputs/apk/release/*.apk
